### ISSUE TITLE
weird ArgumentError

### ISSUE THREAD

**Issue by ghost** [meh/elixir-benchmark#1]
this line
https://github.com/meh/elixir-benchmark/blob/master/lib/benchmark.ex#L80

when that range.first == range.last so when n == 1 aka 
`IO.inspect Benchmark.times(1, do: true)`
I am getting an error at this line in my code saying

```
Failures:

  1) test bench1 (ElixirExhaustSamplesTest)
     ** (ArgumentError) argument error
     at test/elixir_exhaust_samples_test.exs:564
```

But the odd thing is that I've tried this:

``` elixir
IO.inspect Enum.map(1 .. 1, fn x -> x end)
```

in my code and it doesn't fail at all, so do you think it's an elixir bug with macros? or what happens?

Thanks.

**Comment by ghost** [comment]
ok I found the problem, 
https://github.com/meh/elixir-benchmark/blob/master/lib/benchmark.ex#L89

``` elixir
median: Benchmark.Time.at(elem(Enum.at(tests, round(length(tests) / 2)), 0)),
```

that `elem(nil,0)` happens

EDIT: tests is `[{0, true}]` so `Enum.at( [{0, true}] , 1 ) == nil` I guess

EDIT2: found a solution:
replacing `round(length(tests) / 2)` with `div(length(tests), 2)`

**Comment by meh** [comment]
A better solution is knowing what you're passing to times, I added a check to do that, thanks for the report.

**Comment by ghost** [comment]
yeah the best solution is one you don't have to remember, we can't have programs span(shard?) computers and human brains :) they should be in only one of those(computers preferably)
