### ISSUE TITLE
benchmark 0 times executes 2 times

### ISSUE THREAD

**Issue by ghost** [meh/elixir-benchmark#3]
(before and after #2 same thing happens)

``` elixir
IO.inspect Benchmark.times(0, do: IO.puts "done1")
```

shows `done1` twice, as if the parameter was `2` instead of `0`

whereas, any other positive parameter shows `done1` correct number of times (and after #2 passing `1` works too)

**Comment by meh** [comment]
Again, you shouldn't pass wrong things to `Benchmark.times`.

**Comment by ghost** [comment]
:))
